version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test01
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432

  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
